import { createFileRoute, Link } from "@tanstack/react-router";
import { Bookmark, BookmarkCheck, Check, Loader2, MessageCircleHeart, Volume2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { registerDailyLearningActivity } from "@/lib/activity-tracking";
import { getStudentProfile, normalizeLanguage } from "@/lib/profile-context";
import { supabase } from "@/lib/supabase";

export const Route = createFileRoute("/drops")({ component: Drops });

type DailyDrop = { id: string; theme: string; word: string; pronunciation: string | null; translation: string; curiosity: string | null; language: string; color_variant: string };
const temas = ["Cultura", "Culinária", "Música", "Cinema", "Arte", "Expressões", "Pronúncia", "Hábitos", "Tradições"];
const fundo = (cor: string) => cor === "warm" ? "bg-gradient-warm" : cor === "ink" ? "bg-gradient-ink" : "bg-gradient-mia";

function Drops() {
  const [idioma, setIdioma] = useState<string | null>(null);
  const [drops, setDrops] = useState<DailyDrop[]>([]);
  const [salvos, setSalvos] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem("falaclub_saved_drops") || "[]") as string[]; } catch { return []; } });
  const [carregando, setCarregando] = useState(true);
  const [concluidoHoje, setConcluidoHoje] = useState(false);
  const [registrando, setRegistrando] = useState(false);

  useEffect(() => { let ativo = true; (async () => { try { const perfil = await getStudentProfile(); const idiomaPerfil = normalizeLanguage(perfil?.target_language); if (!idiomaPerfil) return; if (ativo) setIdioma(idiomaPerfil); const inicio = new Date(); inicio.setHours(0,0,0,0); const [{ data, error }, { data: atividade, error: atividadeError }] = await Promise.all([supabase.from("daily_drops").select("id, theme, word, pronunciation, translation, curiosity, language, color_variant").eq("language", idiomaPerfil).order("created_at", { ascending: false }), supabase.from("learning_activities").select("skill").eq("user_id", perfil?.id ?? "").eq("skill", "culture").gte("completed_at", inicio.toISOString()).limit(1)]); if (error) throw error; if (atividadeError) throw atividadeError; if (ativo) { setDrops((data ?? []) as DailyDrop[]); setConcluidoHoje((atividade ?? []).length > 0); } } catch (error) { console.error("Erro ao carregar Drops:", error); if (ativo) setDrops([]); } finally { if (ativo) setCarregando(false); } })(); return () => { ativo = false; }; }, []);
  const titulo = useMemo(() => idioma ? `Sua dose diária de ${idioma.toLowerCase()}` : "Sua dose diária de cultura e vocabulário", [idioma]);
  function ouvir(drop: DailyDrop) { if (typeof window === "undefined") return; window.speechSynthesis.cancel(); const fala = new SpeechSynthesisUtterance(`${drop.word}. ${drop.translation}`); fala.lang = drop.language.toLowerCase().includes("fr") ? "fr-FR" : drop.language.toLowerCase().includes("ing") ? "en-US" : drop.language.toLowerCase().includes("esp") ? "es-ES" : drop.language.toLowerCase().includes("ita") ? "it-IT" : "de-DE"; window.speechSynthesis.speak(fala); }
  function alternarSalvar(id: string) { setSalvos((atual) => { const novo = atual.includes(id) ? atual.filter((item) => item !== id) : [...atual, id]; localStorage.setItem("falaclub_saved_drops", JSON.stringify(novo)); return novo; }); }
  async function concluirDrop() { if (concluidoHoje || registrando) return; setRegistrando(true); try { const criada = await registerDailyLearningActivity("culture", 5); if (criada) setConcluidoHoje(true); else setConcluidoHoje(true); } catch (error) { console.error("Erro ao registrar Drop:", error); } finally { setRegistrando(false); } }

  return <AppShell titulo="Drops do idioma" subtitulo={carregando ? "Carregando seu idioma..." : titulo}><div className="flex flex-wrap gap-2">{temas.map(t => <span key={t} className="rounded-full border border-border bg-card px-3 py-1.5 text-xs font-semibold text-muted-foreground">{t}</span>)}</div>{carregando ? <div className="flex justify-center py-16"><Loader2 className="size-7 animate-spin text-primary" /></div> : drops.length === 0 ? <div className="surface-card mt-6 p-8 text-center"><p className="font-display text-lg font-bold">Ainda não há Drops para este idioma.</p><p className="mt-2 text-sm text-muted-foreground">Assim que um novo conteúdo for publicado, ele aparecerá aqui.</p></div> : <><div className="mt-5 flex justify-end"><button onClick={concluirDrop} disabled={concluidoHoje || registrando} className="inline-flex items-center gap-2 rounded-full bg-gradient-brand px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-60">{registrando ? <Loader2 className="size-4 animate-spin" /> : <Check className="size-4" />} {concluidoHoje ? "Drop concluído hoje" : "Concluir Drop de hoje"}</button></div><div className="mt-4 grid gap-5 lg:grid-cols-3">{drops.map(drop => <article key={drop.id} className="surface-card overflow-hidden p-0"><div className={`${fundo(drop.color_variant)} p-6 text-primary-foreground`}><p className="text-xs font-semibold uppercase tracking-[0.16em] opacity-80">{drop.theme}</p><h2 className="mt-2 font-display text-2xl font-bold">{drop.word}</h2>{drop.pronunciation && <p className="text-sm opacity-85">{drop.pronunciation}</p>}</div><div className="p-5"><p className="text-sm font-semibold">{drop.translation}</p>{drop.curiosity && <p className="mt-2 text-sm text-muted-foreground">{drop.curiosity}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={() => ouvir(drop)} className="inline-flex items-center gap-1.5 rounded-full bg-secondary px-3 py-1.5 text-xs font-semibold text-secondary-foreground"><Volume2 className="size-3.5" /> Ouvir</button><button onClick={() => alternarSalvar(drop.id)} aria-pressed={salvos.includes(drop.id)} className="inline-flex items-center gap-1.5 rounded-full bg-secondary px-3 py-1.5 text-xs font-semibold text-secondary-foreground">{salvos.includes(drop.id) ? <BookmarkCheck className="size-3.5" /> : <Bookmark className="size-3.5" />} {salvos.includes(drop.id) ? "Salvo" : "Salvar"}</button><Link to="/mia" className="inline-flex items-center gap-1.5 rounded-full bg-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground"><MessageCircleHeart className="size-3.5" /> Conversar</Link></div></div></article>)}</div></>}</AppShell>;
}
