import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { Loader2, Mic, Send, Square, Volume2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { MiaAvatar } from "@/components/brand";
import { supabase } from "@/lib/supabase";
import { sendMiaMessage, sendMiaVoice } from "@/lib/mia-api";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/mia")({ component: MiaChat });

type ChatMessage = { de: "aluno" | "mia"; texto: string; audio?: string | null };

function MiaChat() {
  const [mensagens, setMensagens] = useState<ChatMessage[]>([{ de: "mia", texto: "Oi! Eu sou a Mia. Bora praticar? ☕" }]);
  const [texto, setTexto] = useState(""); const [loading, setLoading] = useState(false); const [conversationId, setConversationId] = useState<string | null>(null); const [isRecording, setIsRecording] = useState(false); const [erro, setErro] = useState<string | null>(null);
  const recorderRef = useRef<MediaRecorder | null>(null); const chunksRef = useRef<Blob[]>([]);

  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (!data.user) window.location.href = "/login"; }).catch(console.error); }, []);

  function tocarAudio(audioData: string) { const src = audioData.startsWith("http") ? audioData : `data:audio/mpeg;base64,${audioData}`; void new Audio(src).play().catch(console.error); }
  async function enviar(valor: string) { const content = valor.trim(); if (!content || loading) return; setErro(null); setTexto(""); setMensagens((m) => [...m, { de: "aluno", texto: content }]); setLoading(true); try { const r = await sendMiaMessage(content, conversationId); setConversationId(r.conversationId); setMensagens((m) => [...m, { de: "mia", texto: r.reply }]); } catch (e) { setErro(e instanceof Error ? e.message : "Não consegui falar com a Mia agora."); } finally { setLoading(false); } }
  async function enviarAudio(blob: Blob) { setErro(null); setLoading(true); setMensagens((m) => [...m, { de: "aluno", texto: "🎤 Processando seu áudio..." }]); try { const r = await sendMiaVoice(blob, conversationId); setConversationId(r.conversationId); setMensagens((m) => { const copy = [...m]; if (copy.at(-1)?.texto === "🎤 Processando seu áudio...") copy[copy.length - 1] = { de: "aluno", texto: r.userTranscript }; return [...copy, { de: "mia", texto: r.replyText, audio: r.audioBase64 }]; }); if (r.audioBase64) tocarAudio(r.audioBase64); } catch (e) { setErro(e instanceof Error ? e.message : "Não consegui processar seu áudio."); } finally { setLoading(false); } }
  async function startRecording() { if (!navigator.mediaDevices?.getUserMedia || !window.MediaRecorder) { setErro("Seu navegador não oferece gravação de áudio."); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const recorder = new MediaRecorder(stream); recorderRef.current = recorder; chunksRef.current = []; recorder.ondataavailable = (e) => { if (e.data.size) chunksRef.current.push(e.data); }; recorder.onstop = async () => { const blob = new Blob(chunksRef.current, { type: recorder.mimeType || "audio/webm" }); stream.getTracks().forEach((t) => t.stop()); await enviarAudio(blob); }; recorder.start(); setIsRecording(true); } catch { setErro("Não consegui acessar seu microfone. Verifique a permissão."); } }
  function stopRecording() { if (recorderRef.current?.state === "recording") { recorderRef.current.stop(); setIsRecording(false); } }

  return <AppShell titulo="Falar com a Mia" subtitulo="Conversa guiada, correção gentil e zero julgamento"><div className="surface-card flex min-h-[32rem] flex-col overflow-hidden p-0"><div className="flex items-center gap-3 bg-gradient-mia p-4 text-white"><MiaAvatar className="ring-0" /><div><p className="text-sm font-bold">Mia</p><p className="text-xs opacity-85">{isRecording ? "Gravando sua voz... 🎙️" : loading ? "Mia está processando... ☕" : "online · pronta para praticar"}</p></div></div>{erro && <div className="border-b border-red-500/20 bg-red-500/10 px-4 py-2 text-xs text-red-500">{erro}</div>}<div className="flex-1 space-y-3 overflow-y-auto p-4">{mensagens.map((m, i) => <div key={`${i}-${m.texto}`} className={cn("flex gap-2", m.de === "aluno" ? "justify-end" : "justify-start")}>{m.de === "mia" && <MiaAvatar className="size-8 ring-0" />}<div className="flex max-w-[80%] flex-col gap-1"><p className={cn("text-sm leading-relaxed", m.de === "aluno" ? "rounded-2xl rounded-br-sm bg-primary px-4 py-2.5 text-white" : "rounded-2xl rounded-bl-sm bg-secondary px-4 py-2.5")}>{m.texto}</p>{m.audio && <button onClick={() => tocarAudio(m.audio!)} className="flex items-center gap-1 px-1 text-xs text-muted-foreground"><Volume2 className="size-3" />Ouvir novamente</button>}</div></div>)}{loading && <div className="flex items-center gap-2 text-xs text-muted-foreground"><MiaAvatar className="size-6 ring-0" />Mia está pensando...<Loader2 className="size-3 animate-spin" /></div>}</div><form onSubmit={(e) => { e.preventDefault(); void enviar(texto); }} className="border-t border-border p-3"><div className="flex items-center gap-2"><input value={texto} disabled={loading || isRecording} onChange={(e) => setTexto(e.target.value)} placeholder={isRecording ? "Gravando áudio..." : "Escreva ou fale com a Mia..."} className="h-11 flex-1 rounded-full border border-input bg-background px-4 text-sm" /><button type="button" aria-label={isRecording ? "Parar gravação" : "Falar"} disabled={loading} onClick={isRecording ? stopRecording : startRecording} className={cn("flex size-11 items-center justify-center rounded-full border", isRecording ? "border-red-600 bg-red-500 text-white" : "border-input text-muted-foreground")}>{isRecording ? <Square className="size-4 fill-current" /> : <Mic className="size-4" />}</button><button type="submit" disabled={loading || !texto.trim() || isRecording} className="flex size-11 items-center justify-center rounded-full bg-gradient-brand text-white disabled:opacity-50">{loading ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}</button></div></form></div></AppShell>;
}
