import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { BookOpen, Home, Layers, LogOut, MessageCircleHeart, Sparkles, Trophy } from "lucide-react";
import { useEffect, useState, type ReactNode } from "react";
import { toast } from "sonner";
import { getCurrentProfile, signOut, type UserRole } from "@/lib/auth";
import { cn } from "@/lib/utils";
import { Logo, MiaAvatar } from "@/components/brand";

type Item = { to: "/hoje" | "/mia" | "/biblioteca" | "/flashcards" | "/drops" | "/progresso"; label: string; icon: typeof Home };
const nav: Item[] = [{to:"/hoje",label:"Hoje",icon:Home},{to:"/mia",label:"Falar com a Mia",icon:MessageCircleHeart},{to:"/biblioteca",label:"Biblioteca",icon:BookOpen},{to:"/flashcards",label:"Flashcards",icon:Layers},{to:"/drops",label:"Drops do idioma",icon:Sparkles},{to:"/progresso",label:"Progresso",icon:Trophy}];

export function AppShell({titulo,subtitulo,acao,children}:{titulo:string;subtitulo?:string;acao?:ReactNode;children:ReactNode}) {
 const pathname=useRouterState({select:s=>s.location.pathname}), navigate=useNavigate(); const [role,setRole]=useState<UserRole|null>(null); const [loggingOut,setLoggingOut]=useState(false);
 useEffect(()=>{let alive=true; getCurrentProfile().then(p=>alive&&setRole(p?.role??null)).catch(console.error); return()=>{alive=false}},[]);
 async function logout(){if(loggingOut)return;setLoggingOut(true);try{await signOut();await navigate({to:"/login"})}catch(e){console.error(e);toast.error("Não foi possível sair da conta.");setLoggingOut(false)}}
 return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col gap-6 overflow-y-auto bg-sidebar px-4 py-6 text-sidebar-foreground lg:flex"><div className="rounded-2xl bg-sidebar-accent/60 px-3 py-3"><Logo/></div><nav className="flex flex-1 flex-col gap-1">{nav.map(i=><Link key={i.to} to={i.to} className={cn("flex items-center gap-3 rounded-xl px-3 py-2 text-sm font-medium",pathname===i.to?"bg-sidebar-primary text-sidebar-primary-foreground":"hover:bg-sidebar-accent")}><i.icon className="size-4"/>{i.label}</Link>)}</nav><Link to="/mia" className="flex items-center gap-3 rounded-2xl bg-gradient-mia px-3 py-3 text-white"><MiaAvatar className="size-9 ring-0"/><span className="text-xs"><b className="block">Mia está online</b><span>Bora praticar 5 min?</span></span></Link><button type="button" onClick={()=>void logout()} disabled={loggingOut} className="flex items-center gap-3 rounded-xl px-3 py-2 text-sm"><LogOut className="size-4"/>{loggingOut?"Saindo...":"Sair"}</button></aside><div className="lg:pl-64"><header className="sticky top-0 z-30 border-b border-border/70 bg-background/85 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="min-w-0"><div className="lg:hidden"><Logo/></div><h1 className="mt-1 truncate text-xl font-bold sm:text-2xl">{titulo}</h1>{subtitulo&&<p className="truncate text-sm text-muted-foreground">{subtitulo}</p>}</div><div>{acao}</div></div></header><main className="mx-auto max-w-6xl px-4 pb-28 pt-6 sm:px-6 lg:pb-12">{children}</main></div><nav className="fixed inset-x-0 bottom-0 z-40 border-t border-border bg-card/95 backdrop-blur lg:hidden"><div className="mx-auto flex max-w-lg justify-around px-2 py-2">{nav.slice(0,4).map(i=><Link key={i.to} to={i.to} className={cn("flex flex-col items-center gap-1 px-2 py-1 text-[11px]",pathname===i.to?"text-primary":"text-muted-foreground")}><i.icon className="size-5"/>{i.label}</Link>)}<button type="button" onClick={()=>void logout()} className="flex flex-col items-center gap-1 px-2 py-1 text-[11px] text-muted-foreground"><LogOut className="size-5"/>Sair</button></div></nav></div>;
}
export function SectionCard({titulo,descricao,acao,children,className}:{titulo?:string;descricao?:string;acao?:ReactNode;children:ReactNode;className?:string}){return <section className={cn("surface-card p-5",className)}>{titulo&&<header className="mb-4 flex items-start justify-between gap-3"><div><h2 className="text-base font-bold">{titulo}</h2>{descricao&&<p className="text-sm text-muted-foreground">{descricao}</p>}</div>{acao}</header>}{children}</section>}
export function Stat({rotulo,valor,delta}:{rotulo:string;valor:string;delta?:string}){return <div className="surface-card p-4"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{rotulo}</p><p className="mt-2 font-display text-2xl font-bold">{valor}</p>{delta&&<p className="mt-1 text-xs font-semibold text-success">{delta}</p>}</div>}
