/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as EscolaRouteImport } from './routes/escola'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as HojeRouteImport } from './routes/hoje'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MiaRouteImport } from './routes/mia'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as ProgressoRouteImport } from './routes/progresso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolaRoute = EscolaRouteImport.update({
  id: '/escola',
  path: '/escola',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const HojeRoute = HojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MiaRoute = MiaRouteImport.update({
  id: '/mia',
  path: '/mia',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/creator': typeof CreatorRoute
  '/drops': typeof DropsRoute
  '/escola': typeof EscolaRoute
  '/flashcards': typeof FlashcardsRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/mia': typeof MiaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/creator': typeof CreatorRoute
  '/drops': typeof DropsRoute
  '/escola': typeof EscolaRoute
  '/flashcards': typeof FlashcardsRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/mia': typeof MiaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biblioteca': typeof BibliotecaRoute
  '/creator': typeof CreatorRoute
  '/drops': typeof DropsRoute
  '/escola': typeof EscolaRoute
  '/flashcards': typeof FlashcardsRoute
  '/hoje': typeof HojeRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/mia': typeof MiaRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/professor': typeof ProfessorRoute
  '/progresso': typeof ProgressoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biblioteca'
    | '/creator'
    | '/drops'
    | '/escola'
    | '/flashcards'
    | '/hoje'
    | '/login'
    | '/master'
    | '/mia'
    | '/onboarding'
    | '/perfil'
    | '/professor'
    | '/progresso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biblioteca'
    | '/creator'
    | '/drops'
    | '/escola'
    | '/flashcards'
    | '/hoje'
    | '/login'
    | '/master'
    | '/mia'
    | '/onboarding'
    | '/perfil'
    | '/professor'
    | '/progresso'
  id:
    | '__root__'
    | '/'
    | '/biblioteca'
    | '/creator'
    | '/drops'
    | '/escola'
    | '/flashcards'
    | '/hoje'
    | '/login'
    | '/master'
    | '/mia'
    | '/onboarding'
    | '/perfil'
    | '/professor'
    | '/progresso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CreatorRoute: typeof CreatorRoute
  DropsRoute: typeof DropsRoute
  EscolaRoute: typeof EscolaRoute
  FlashcardsRoute: typeof FlashcardsRoute
  HojeRoute: typeof HojeRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  MiaRoute: typeof MiaRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  ProfessorRoute: typeof ProfessorRoute
  ProgressoRoute: typeof ProgressoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escola': {
      id: '/escola'
      path: '/escola'
      fullPath: '/escola'
      preLoaderRoute: typeof EscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoje': {
      id: '/hoje'
      path: '/hoje'
      fullPath: '/hoje'
      preLoaderRoute: typeof HojeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mia': {
      id: '/mia'
      path: '/mia'
      fullPath: '/mia'
      preLoaderRoute: typeof MiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BibliotecaRoute: BibliotecaRoute,
  CreatorRoute: CreatorRoute,
  DropsRoute: DropsRoute,
  EscolaRoute: EscolaRoute,
  FlashcardsRoute: FlashcardsRoute,
  HojeRoute: HojeRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  MiaRoute: MiaRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  ProfessorRoute: ProfessorRoute,
  ProgressoRoute: ProgressoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
